apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: anonymizer
  namespace: anonymizer
spec:
  type: "oci"
  interval: 168h
  url: oci://cr.yandex/crp2cvbrp76d7dmfegco/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: anonymizer
  namespace: anonymizer
spec:
  chart:
    spec:
      chart: anonymizer-app
      version: '3.0.0'
      sourceRef:
        kind: HelmRepository
        name: anonymizer
  interval: 168h
  values:
    # victoriametrics:  #will replace prometheus CRs with victoriametrics CRs
    #   enabled: true
    environmentName: sigma  #will be provided by Mindbox manager
    tenant: anonymizer-demo  #will be provided by Mindbox manager
    mandatoryEnv:
      s3:
        private:
          serviceUrl: "https://s3.yandexcloud.net/"
          bucketName: "anonymizer-test-stand-bucket"
          accessKey:
            valueFrom:
              secretKeyRef:
                name: manual-secrets
                key: S3__Private__AccessKey
          secretKey:
            valueFrom:
              secretKeyRef:
                name: manual-secrets
                key: S3__Private__SecretKey
        public:
          serviceUrl: "https://s3.yandexcloud.net/"
          bucketName: "bucket-anonymizer-clients-public"
          accessKey:
            valueFrom:
              secretKeyRef:
                name: manual-secrets
                key: S3__Public__AccessKey
          secretKey:
            valueFrom:
              secretKeyRef:
                name: manual-secrets
                key: S3__Public__SecretKey
      postgreSqlDatabase:
        username:
          valueFrom:
            secretKeyRef:
              name: db-anonymizer-anonymizer-user-password
              key: username
        password:
          valueFrom:
            secretKeyRef:
              name: db-anonymizer-anonymizer-user-password
              key: password
        connectionString: "Host=c-c9q0iffnprn9ic4nqc9k.rw.mdb.yandexcloud.net ;Database=anonymizer-demo-v2;SSL Mode=Require;Port=6432;Maximum Pool Size=200;Enlist=false;"
      mindboxAuth:
        anonymizerPrivateKey:
          valueFrom:
            secretKeyRef:
              name: manual-secrets
              key: MindboxAuth__AnonymizerPrivateKey
        mindboxPublicKey:
          valueFrom:
            secretKeyRef:
              name: manual-secrets
              key: MindboxAuth__MindboxPublicKey
    services:
      # # Пример настройки affinity & tolerations
      #   nodeAffinity:
      #     preferredDuringSchedulingIgnoredDuringExecution:
      #     - weight: 100
      #       preference:
      #         matchExpressions:
      #         - key: node-type
      #           operator: In
      #           values:
      #           - compute-optimized
      # tolerations:
      # - key: "node-type"
      #   operator: "Equal"
      #   value: "compute-optimized"
      #   effect: "NoSchedule"
      roles:
        regular:
          replicas: "3"
          resources:
            limits:
              memory: "512Mi"
            requests:
              cpu: "500m"
              memory: "256Mi"
        important:
          replicas: "3"
          resources:
            limits:
              memory: "512Mi"
            requests:
              cpu: "500m"
              memory: "256Mi"
    lrt:
      # # Пример настройки affinity & tolerations
      #   nodeAffinity:
      #     preferredDuringSchedulingIgnoredDuringExecution:
      #     - weight: 100
      #       preference:
      #         matchExpressions:
      #         - key: node-type
      #           operator: In
      #           values:
      #           - compute-optimized
      # tolerations:
      # - key: "node-type"
      #   operator: "Equal"
      #   value: "compute-optimized"
      #   effect: "NoSchedule"
      roles:
        default:
          replicas: "3"
          resources:
            limits:
              memory: "1024Mi"
            requests:
              cpu: "800m"
              memory: "256Mi"
    # migrations:  #If u are using YC managed postgresql set PostgreSqlDatabase__ApplyMaintenanceMigrations env to false like this:
    #   env:
    #     - name: PostgreSqlDatabase__ApplyMaintenanceMigrations
    #       value: "false"