{
 "title": "Anonymizer - Basic Service Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "app",
    "label": "app",
    "query": {
     "query": "label_values(http_requests_received_total{namespace=\"anonymizer\"},app)"
    }
   },
   {
    "name": "endpoint",
    "label": "endpoint",
    "query": {
     "query": "label_values(http_requests_received_total{app=\"$app\"},exported_endpoint)"
    }
   },
   {
    "name": "method",
    "label": "method",
    "query": {
     "query": "label_values(http_requests_received_total{app=\"$app\"},method)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{app=\"$app\", exported_endpoint=~\"$endpoint\", method=~\"$method\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{app=\"$app\", exported_endpoint=~\"$endpoint\", method=~\"$method\"}[1m])) by (le))"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(http_request_duration_seconds_bucket{code=~\"[1-4]..\", le=\"0.512\", app=\"$app\", exported_endpoint=~\"$endpoint\", method=~\"$method\"}[$__rate_interval])) + sum(rate(http_request_duration_seconds_bucket{code=~\"[1-4]..\", le=\"2.048\", app=\"$app\", exported_endpoint=~\"$endpoint\", method=~\"$method\"}[$__rate_interval]))) / 2 / sum(rate(http_request_duration_seconds_count{app=\"$app\", exported_endpoint=~\"$endpoint\", method=~\"$method\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(http_requests_received_total{code=~\"[5]..\", app=\"$app\", exported_endpoint=~\"$endpoint\", method=~\"$method\"}[1m])) OR on() vector(0)) / sum(rate(http_requests_received_total{app=\"$app\", exported_endpoint=~\"$endpoint\", method=~\"$method\"}[1m]))"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "timeseries",
   "description": "В случае, если для МКС отсутствуют данные по перцентилям в этой панельке, надо обновить helm чарт mindbox/commons-app в МКС до версии не ниже 4.2.1",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket{app=\"$app\", exported_endpoint=~\"$endpoint\", method=~\"$method\"}[$__rate_interval])) by (le))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{app=\"$app\", exported_endpoint=~\"$endpoint\", method=~\"$method\"}[$__rate_interval])) by (le))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{app=\"$app\", exported_endpoint=~\"$endpoint\", method=~\"$method\"}[$__rate_interval])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{app=\"$app\", exported_endpoint=~\"$endpoint\", method=~\"$method\"}[$__rate_interval])) / sum(rate(http_request_duration_seconds_count{app=\"$app\", exported_endpoint=~\"$endpoint\", method=~\"$method\"}[$__rate_interval]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Error rate & Apdex",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by (code) (rate(http_requests_received_total{code=~\"[45]..\", app=\"$app\", exported_endpoint=~\"$endpoint\", method=~\"$method\"}[$__rate_interval])) OR on() vector(0)) / scalar(sum (rate(http_requests_received_total{app=\"$app\", exported_endpoint=~\"$endpoint\", method=~\"$method\"}[$__rate_interval])))",
     "legendFormat": "{{code}}"
    },
    {
     "expr": "(sum(rate(http_request_duration_seconds_bucket{code=~\"[1-4]..\", le=\"0.512\", app=\"$app\", exported_endpoint=~\"$endpoint\", method=~\"$method\"}[$__rate_interval])) + sum(rate(http_request_duration_seconds_bucket{code=~\"[1-4]..\", le=\"2.048\", app=\"$app\", exported_endpoint=~\"$endpoint\", method=~\"$method\"}[$__rate_interval]))) / 2 / sum(rate(http_request_duration_seconds_count{app=\"$app\", exported_endpoint=~\"$endpoint\", method=~\"$method\"}[$__rate_interval]))",
     "legendFormat": "Apdex"
    }
   ]
  },
  {
   "title": "Requests / Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{app=\"$app\", exported_endpoint=~\"$endpoint\", method=~\"$method\"}[$__rate_interval])) by (method, exported_endpoint)",
     "legendFormat": "{{method}} {{exported_endpoint}}"
    }
   ]
  },
  { "title": "Per poddiagnostics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Requests / Second by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{app=\"$app\", exported_endpoint=~\"$endpoint\", method=~\"$method\"}[$__rate_interval])) by (method, exported_endpoint, pod_ip)",
     "legendFormat": "{{pod_ip}}:{{method}} {{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "Response time 95 percentile by pod",
   "type": "timeseries",
   "description": "В случае, если для МКС отсутствуют данные по перцентилям в этой панельке, надо обновить helm чарт mindbox/commons-app в МКС до версии не ниже 4.2.1",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum (rate(http_request_duration_seconds_bucket{app=\"$app\", exported_endpoint=~\"$endpoint\", method=~\"$method\"}[$__rate_interval])) by (le, pod_ip))",
     "legendFormat": "{{pod_ip}}"
    }
   ]
  }
 ]
}