{
 "title": "Anonymizer - Main Metrics",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(http_request_duration_seconds_count,cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(http_request_duration_seconds_count{cluster=~\"$cluster\"},namespace)"
    }
   },
   {
    "name": "service",
    "label": "service",
    "query": {
     "query": "label_values(http_request_duration_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\"},service)"
    }
   },
   {
    "name": "route",
    "label": "route",
    "query": {
     "query": "label_values(http_request_duration_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\"},exported_endpoint)"
    }
   }
  ]
 },
 "panels": [
  { "title": "RPS / Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RPS запросов",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (code,exported_endpoint) (rate(http_request_duration_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\",exported_endpoint=~\"$route\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Среднее время выполнения запроса",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(sum by (exported_endpoint) (rate(http_request_duration_seconds_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\", exported_endpoint=~\"$route\"}[$__rate_interval]))\n/\nsum by (exported_endpoint) (rate(http_request_duration_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\", exported_endpoint=~\"$route\"}[$__rate_interval])))",
     "legendFormat": "Общее (T) {{ exported_endpoint }}"
    },
    {
     "expr": "sum by (path) (rate(anonymizer_processing_duration_seconds_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\", path=~\"$route\"}[$__rate_interval]))\n/\nsum by (path) (rate(anonymizer_processing_duration_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\", path=~\"$route\"}[$__rate_interval]))",
     "legendFormat": "В анонимизаторе (Ta) {{ path }}"
    }
   ]
  },
  {
   "title": "Коды ответов MindboxApi и Anonymizer",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum by(path, code) (increase(api_response_counter{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\", path=~\"$route\"}[$__rate_interval])) > 0",
     "legendFormat": "MindboxApi ({{path}}:{{code}})"
    },
    {
     "expr": "sum by(path, code) (increase(anonymizer_response_counter{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\", path=~\"$route\"}[$__rate_interval])) > 0",
     "legendFormat": "Anonymizer ({{path}}:{{code}})"
    }
   ]
  },
  {
   "title": "BulkOperations SLO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Время выполнения запроса синк операций",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 16, "x": 0, "y": 130 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.95,\n  sum by (path, le) (\n      rate(total_request_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\", path=\"/v3/operations/bulk\"}[$__rate_interval])\n    )\n)",
       "legendFormat": "T, 95%"
      },
      {
       "expr": "histogram_quantile(\n  0.95,\n  sum by (path, le) (\n      rate(anonymizer_proxy_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\", path=\"/v3/operations/bulk\"}[$__rate_interval])\n    )\n)",
       "legendFormat": "Tapi, 95%"
      },
      {
       "expr": "histogram_quantile(\n  0.95,\n  sum by (path, le) (\n      rate(anonymizer_processing_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\", path=\"/v3/operations/bulk\"}[$__rate_interval])\n    )\n)",
       "legendFormat": "Ta, 95%"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 21, "w": 8, "x": 16, "y": 130 },
     "options": {
      "content": "# SLO на время обработки запроса анонимизатором\n\n<br>\n\n| Тип               | SLO Ta (p95)  |\n|:------------------|---------------|\n|Синхронные вызовы  |5 s         |\n|Асинхронные вызовы |5 s         |\n\n<br>\n\nT - общее время обработки запроса, мс\n\nTa - время обработки запроса анонимизатором, мс\n\nTapi - время обработки запроса api.mindbox.ru, мс\n\nTa = T-Tapi"
     }
    },
    {
     "title": "Время выполнения запроса асинк операций",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 16, "x": 0, "y": 141 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.95,\n  sum by (path, le) (\n      rate(total_request_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\", path=\"/v3/operations/bulk\"}[$__rate_interval])\n    )\n)",
       "legendFormat": "T, 95%"
      },
      {
       "expr": "histogram_quantile(\n  0.95,\n  sum by (path, le) (\n      rate(anonymizer_proxy_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\", path=\"/v3/operations/bulk\"}[$__rate_interval])\n    )\n)",
       "legendFormat": "Tapi, 95%"
      },
      {
       "expr": "histogram_quantile(\n  0.95,\n  sum by (path, le) (\n      rate(anonymizer_processing_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\", path=\"/v3/operations/bulk\"}[$__rate_interval])\n    )\n)",
       "legendFormat": "Ta, 95%"
      }
     ]
    },
    {
     "title": "Процент успешных деанонимизаций",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 16, "x": 0, "y": 151 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(sum by (path) (rate(api_response_counter{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\", code=\"200\", path=\"/v3/operations/bulk\"}[$__rate_interval]))\n/\nsum by (path) (rate(anonymizer_response_counter{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\", code=\"200\", path=\"/v3/operations/bulk\"}[$__rate_interval])))\n* 100",
       "legendFormat": "{{path}}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 151 },
     "options": {
      "content": "# SLO на процент успешных деанонимизаций\n\n<br>\n\n| Тип               | SLO, %|\n|:------------------|-------|\n|Синхронные вызовы  |99.95  |\n|Асинхронные вызовы |99.8   |\n\n<br>\n\nCapi - количество успешных ответов из api.mindbox.ru\n\nCa - количество успешных ответов анонимизатора\n\nP - процент успешных деанонимизированных запросов, %\n\nP = Capi/Cv"
     }
    }
   ]
  },
  {
   "title": "Mailings proxy SLO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Время выполнения команд на отправку mailings",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 17, "x": 0, "y": 162 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.95,\n  sum by (path, le) (\n      rate(total_request_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\", path=\"/customerData/send\"}[$__rate_interval])\n    )\n)",
       "legendFormat": "T, 95%"
      },
      {
       "expr": "histogram_quantile(\n  0.95,\n  sum by (path, le) (\n      rate(anonymizer_proxy_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\", path=\"/customerData/send\"}[$__rate_interval])\n    )\n)",
       "legendFormat": "Tapi, 95%"
      },
      {
       "expr": "histogram_quantile(\n  0.95,\n  sum by (path, le) (\n      rate(anonymizer_processing_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\", path=\"/customerData/send\"}[$__rate_interval])\n    )\n)",
       "legendFormat": "Ta, 95%"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 10, "w": 7, "x": 17, "y": 162 },
     "options": {
      "content": "# SLO на время обработки запроса рассылки анонимизатором\n\n<br>\n\n| Тип               | SLO Ta (p95)  |\n|:------------------|---------------|\n|Синхронные вызовы  |200 ms         |\n\n\n<br>\n\nT - общее время обработки запроса, мс\n\nTa - время обработки запроса анонимизатором, мс\n\nTapi - время обработки запроса api.mindbox.ru, мс\n\nTa = T-Tapi"
     }
    },
    {
     "title": "Процент успешных деанонимизаций",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 17, "x": 0, "y": 172 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(sum by (path) (rate(api_response_counter{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\", code=\"200\", path=\"/customerData/send\"}[$__rate_interval]))\n/\nsum by (path) (rate(anonymizer_response_counter{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\", code=\"200\", path=\"/customerData/send\"}[$__rate_interval])))\n* 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "New panel",
     "type": "text",
     "gridPos": { "h": 11, "w": 7, "x": 17, "y": 172 },
     "options": {
      "content": "# SLO на процент успешных деанонимизаций\n\n<br>\n\n| Тип               | SLO, %|\n|:------------------|-------|\n|Синхронные вызовы  |99.95  |\n\n<br>\n\nCapi - количество успешных ответов из апи\n\nCa - количество успешных ответов анонимизатора\n\nP - процент успешных деанонимизированных запросов, %\n\nP = Capi/Cv"
     }
    }
   ]
  },
  {
   "title": "Operations proxy SLO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Время выполнения запроса синк операций",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 17, "x": 0, "y": 184 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.95,\n  sum by (path, le) (\n      rate(total_request_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\", path=~\"/v3/(js/)?operations/sync\"}[$__rate_interval])\n    )\n)",
       "legendFormat": "T, 95%"
      },
      {
       "expr": "histogram_quantile(\n  0.95,\n  sum by (path, le) (\n      rate(anonymizer_proxy_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\", path=~\"/v3/(js/)?operations/sync\"}[$__rate_interval])\n    )\n)",
       "legendFormat": "Tapi, 95%"
      },
      {
       "expr": "histogram_quantile(\n  0.95,\n  sum by (path, le) (\n      rate(anonymizer_processing_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\", path=~\"/v3/(js/)?operations/sync\"}[$__rate_interval])\n    )\n)",
       "legendFormat": "Ta, 95%"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 16, "w": 7, "x": 17, "y": 184 },
     "options": {
      "content": "# SLO на время обработки запроса анонимизатором\n\n<br>\n\n| Тип               | SLO Ta (p95)  |\n|:------------------|---------------|\n|Синхронные вызовы  |200 ms         |\n|Асинхронные вызовы |500 ms         |\n\n<br>\n\nT - общее время обработки запроса, мс\n\nTa - время обработки запроса анонимизатором, мс\n\nTapi - время обработки запроса api.mindbox.ru, мс\n\nTa = T-Tapi"
     }
    },
    {
     "title": "Время выполнения запроса асинк операций",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 17, "x": 0, "y": 192 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.95,\n  sum by (path, le) (\n      rate(total_request_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\", path=~\"/v3/(js/)?operations/async\"}[$__rate_interval])\n    )\n)",
       "legendFormat": "T, 95%"
      },
      {
       "expr": "histogram_quantile(\n  0.95,\n  sum by (path, le) (\n      rate(anonymizer_proxy_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\", path=~\"/v3/(js/)?operations/async\"}[$__rate_interval])\n    )\n)",
       "legendFormat": "Tapi, 95%"
      },
      {
       "expr": "histogram_quantile(\n  0.95,\n  sum by (path, le) (\n      rate(anonymizer_processing_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\", path=~\"/v3/(js/)?operations/async\"}[$__rate_interval])\n    )\n)",
       "legendFormat": "Ta, 95%"
      }
     ]
    },
    {
     "title": "Процент успешных деанонимизаций",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 17, "x": 0, "y": 200 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(sum by (path) (rate(api_response_counter{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\", code=\"200\", path=~\"/v3/(js/)?operations/async\"}[$__rate_interval]))\n/\nsum by (path) (rate(anonymizer_response_counter{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\", code=\"200\", path=~\"/v3/(js/)?operations/async\"}[$__rate_interval])))\n* 100",
       "legendFormat": "{{path}}"
      },
      {
       "expr": "(sum by (path) (rate(api_response_counter{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\", code=\"200\", path=~\"/v3/(js/)?operations/sync\"}[$__rate_interval]))\n/\nsum by (path) (rate(anonymizer_response_counter{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\", code=\"200\", path=~\"/v3/(js/)?operations/sync\"}[$__rate_interval])))\n* 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 11, "w": 7, "x": 17, "y": 200 },
     "options": {
      "content": "# SLO на процент успешных деанонимизаций\n\n<br>\n\n| Тип               | SLO, %|\n|:------------------|-------|\n|Синхронные вызовы  |99.95  |\n|Асинхронные вызовы |99.8   |\n\n<br>\n\nCapi - количество успешных ответов из api.mindbox.ru\n\nCa - количество успешных ответов анонимизатора\n\nP - процент успешных деанонимизированных запросов, %\n\nP = Capi/Cv"
     }
    }
   ]
  },
  {
   "title": "Webhooks proxy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Время выполнения запроса вебхуков",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 17, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.95,\n  sum by (path, le) (\n      rate(total_request_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\", path=\"/webhooks/send\"}[$__rate_interval])\n    )\n)",
       "legendFormat": "T, 95%"
      },
      {
       "expr": "histogram_quantile(\n  0.95,\n  sum by (path, le) (\n      rate(anonymizer_proxy_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\", path=\"/webhooks/send\"}[$__rate_interval])\n    )\n)",
       "legendFormat": "Tapi, 95%"
      },
      {
       "expr": "histogram_quantile(\n  0.95,\n  sum by (path, le) (\n      rate(anonymizer_processing_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\", path=\"/webhooks/send\"}[$__rate_interval])\n    )\n)",
       "legendFormat": "Ta, 95%"
      }
     ]
    }
   ]
  },
  {
   "title": "Deanonymization failure",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Deanonymization errors per second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(data_deanonymization_attempts_total{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\", result=\"failure\"}[$__rate_interval]))",
       "legendFormat": "errors/sec"
      }
     ]
    },
    {
     "title": "Top integrations by error rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "topk(\n  20,\n  sum by (mechanic_name) (\n    rate(data_deanonymization_attempts_total{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\", result=\"failure\"}[$__rate_interval])\n  )\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Errors by mechanic type",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 47 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum by (mechanic_type) (\n  rate(data_deanonymization_attempts_total{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\", result=\"failure\"}[$__rate_interval])\n)",
       "legendFormat": "{{mechanic_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Insert conflicts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Insert conflict events per second",
     "type": "timeseries",
     "description": "Конфликты при вставке анонимизированных персональных данных (например, duplicate_key при конкурентной вставке одного и того же значения).",
     "gridPos": { "h": 8, "w": 16, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by (table, event_type) (rate(anonymizer_insert_conflict_events_total{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\"}[$__rate_interval]))",
       "legendFormat": "{{table}}: {{event_type}}"
      }
     ]
    },
    {
     "title": "Insert conflicts over time range",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(sum by (table, event_type) (increase(anonymizer_insert_conflict_events_total{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\"}[$__range])))",
       "legendFormat": "{{table}}: {{event_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Files import/export",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Files processing",
     "type": "timeseries",
     "description": "Количество файлов импорта/экспорта за интервал: начатые, успешно обработанные и доставленные, упавшие и пропущенные.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (direction) (increase(anonymizer_files_started_total{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\"}[$__rate_interval]))",
       "legendFormat": "started {{direction}}"
      },
      {
       "expr": "sum by (direction) (increase(anonymizer_files_succeeded_total{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\"}[$__rate_interval]))",
       "legendFormat": "succeeded {{direction}}"
      },
      {
       "expr": "sum by (direction) (increase(anonymizer_files_failed_total{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\"}[$__rate_interval]))",
       "legendFormat": "failed {{direction}}"
      },
      {
       "expr": "sum by (direction) (increase(anonymizer_files_skipped_total{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\"}[$__rate_interval]))",
       "legendFormat": "skipped {{direction}}"
      }
     ]
    },
    {
     "title": "Failed files by reason",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (direction, reason) (increase(anonymizer_files_failed_total{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\"}[$__rate_interval]))",
       "legendFormat": "{{direction}}: {{reason}}"
      }
     ]
    },
    {
     "title": "Skipped files by reason",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (direction, reason) (increase(anonymizer_files_skipped_total{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\"}[$__rate_interval]))",
       "legendFormat": "{{direction}}: {{reason}}"
      }
     ]
    },
    {
     "title": "File transfer duration",
     "type": "timeseries",
     "description": "Время обработки одного файла импорта/экспорта от начала до конца. Верхний бакет гистограммы — 600 s.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by (le, direction) (rate(anonymizer_file_transfer_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\"}[$__rate_interval])))",
       "legendFormat": "{{direction}} p50"
      },
      {
       "expr": "histogram_quantile(0.95, sum by (le, direction) (rate(anonymizer_file_transfer_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\"}[$__rate_interval])))",
       "legendFormat": "{{direction}} p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le, direction) (rate(anonymizer_file_transfer_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\"}[$__rate_interval])))",
       "legendFormat": "{{direction}} p99"
      }
     ]
    },
    {
     "title": "Average file transfer duration by result",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (direction, result) (rate(anonymizer_file_transfer_duration_seconds_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\"}[$__rate_interval]))\n/\nsum by (direction, result) (rate(anonymizer_file_transfer_duration_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\"}[$__rate_interval]))",
       "legendFormat": "{{direction}}: {{result}}"
      }
     ]
    },
    {
     "title": "Top endpoints by failed files over time range",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(10, sum by (direction, operation_system_name, endpoint_id) (increase(anonymizer_files_failed_total{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\"}[$__range])) > 0)",
       "legendFormat": "{{direction}} {{operation_system_name}} / {{endpoint_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Auth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Login flow",
     "type": "timeseries",
     "description": "Вход через IdP (OIDC или SAML): инициированные логины, успешные входы, упавшие колбэки и использованные pending-транзакции.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (interactive) (increase(anonymizer_auth_login_initiated_total{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\"}[$__rate_interval]))",
       "legendFormat": "login initiated (interactive={{interactive}})"
      },
      {
       "expr": "sum(increase(anonymizer_auth_successful_login_duration_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\"}[$__rate_interval]))",
       "legendFormat": "successful login"
      },
      {
       "expr": "sum(increase(anonymizer_auth_callback_failed_total{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\"}[$__rate_interval]))",
       "legendFormat": "callback failed"
      },
      {
       "expr": "sum(increase(anonymizer_auth_pending_tx_consumed_total{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\"}[$__rate_interval]))",
       "legendFormat": "pending tx consumed"
      }
     ]
    },
    {
     "title": "Successful login duration",
     "type": "timeseries",
     "description": "Время от начала логина до создания сессии (только успешные входы).",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by (le, protocol) (rate(anonymizer_auth_successful_login_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\"}[$__rate_interval])))",
       "legendFormat": "{{protocol}} p50"
      },
      {
       "expr": "histogram_quantile(0.95, sum by (le, protocol) (rate(anonymizer_auth_successful_login_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\"}[$__rate_interval])))",
       "legendFormat": "{{protocol}} p95"
      }
     ]
    },
    {
     "title": "Active sessions and pending transactions",
     "type": "timeseries",
     "description": "Значения считаются по базе и одинаковы на всех подах, поэтому берётся max, а не sum.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(anonymizer_auth_active_sessions{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\"})",
       "legendFormat": "active sessions"
      },
      {
       "expr": "max(anonymizer_auth_pending_tx_count{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\"})",
       "legendFormat": "pending tx"
      }
     ]
    },
    {
     "title": "Auth gauges staleness",
     "type": "timeseries",
     "description": "Сколько секунд прошло с последнего успешного обновления гейджей active sessions и pending tx. Рост значения означает, что фоновое обновление не работает.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "time() - (max(anonymizer_auth_active_sessions_last_updated_timestamp_seconds{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\"}) > 0)",
       "legendFormat": "active sessions"
      },
      {
       "expr": "time() - (max(anonymizer_auth_pending_tx_last_updated_timestamp_seconds{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\"}) > 0)",
       "legendFormat": "pending tx"
      }
     ]
    },
    {
     "title": "Cleanup jobs: deleted rows",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(anonymizer_auth_session_cleanup_deleted_total{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\"}[$__rate_interval]))",
       "legendFormat": "expired sessions"
      },
      {
       "expr": "sum(increase(anonymizer_auth_pending_tx_cleanup_deleted_total{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\"}[$__rate_interval]))",
       "legendFormat": "expired pending tx"
      }
     ]
    },
    {
     "title": "Cleanup jobs duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by (le) (rate(anonymizer_auth_session_cleanup_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\"}[$__rate_interval])))",
       "legendFormat": "session cleanup p95"
      },
      {
       "expr": "histogram_quantile(0.95, sum by (le) (rate(anonymizer_auth_pending_tx_cleanup_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\"}[$__rate_interval])))",
       "legendFormat": "pending tx cleanup p95"
      }
     ]
    },
    {
     "title": "SAML certificate rotations",
     "type": "timeseries",
     "description": "Смены сертификата IdP, обнаруженные при обновлении SAML-метаданных.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(anonymizer_auth_saml_cert_rotated_total{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\"}[$__rate_interval]))",
       "legendFormat": "rotations"
      }
     ]
    }
   ]
  }
 ]
}